services:
  - type: web
    name: moviestreamapp-fe
    env: static
    buildCommand: npm ci && npm run build
    staticPublishPath: build
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=0, must-revalidate
      - path: /static/*
        name: Cache-Control
        value: public, max-age=31536000, immutable