spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    show-sql: ${JPA_SHOW_SQL:false}
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
      physical_naming_strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      implicit_naming_strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl

server:
  port: ${PORT:8080}

jwt:
  signerKey: ${JWT_SIGNER_KEY:}
  valid-duration: ${JWT_VALID_DURATION:36000}
  refreshable-duration: ${JWT_REFRESHABLE_DURATION:360000}
  algorithm: ${JWT_ALGORITHM:HS256}
  
recommendation:
  modelBasePath: ${MODEL_BASE_PATH:classpath:models/gcn_model_scripted.pt}
  cache:
    enabled: ${RECOMMENDATION_CACHE_ENABLED:true}
    size: ${RECOMMENDATION_CACHE_SIZE:1000}