spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:moviestream}?useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
  jpa:
    show-sql: ${JPA_SHOW_SQL:false}
    hibernate:
      ddl-auto: none   # prevent Hibernate from performing automatic schema changes on startup

server:
  port: ${SERVER_PORT:8080}

jwt:
  signerKey: ${JWT_SIGNER_KEY:}
recommendation:
  modelBasePath: ${MODEL_BASE_PATH:classpath:models/gcn_model_scripted.pt}
  cache:
    enabled: ${RECOMMENDATION_CACHE_ENABLED:true}
    size: ${RECOMMENDATION_CACHE_SIZE:1000}