spring:
  datasource:
    url: jdbc:mysql://localhost:3306/MOVIE_STREAMING_APP?useSSL=false&serverTimezone=UTC
    username: root
    password: 1
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

server:
  port: 8080

jwt:
  signerKey: "Nn+SxidQSS72KF1eLyV9UMzBco/U/zauCadj15iEEStFO3uTePbAlkssV7sfPqvp"
  valid-duration: 36000
  refreshable-duration: 360000

